"""Centralized CRM enums — single source of truth for CRM-related enumerations.

Only enums actively imported from this module are kept.
Model-specific enums (LeadStatus, CampaignStatus, etc.) live in their respective model files.
"""
import enum


class FollowUpStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONTACTED = "CONTACTED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    RESCHEDULED = "RESCHEDULED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    SCHEDULED = "SCHEDULED"
    NO_SHOW = "NO_SHOW"
    OVERDUE = "OVERDUE"
    ESCALATED = "ESCALATED"
    INTERESTED = "INTERESTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    NEEDS_MORE_TIME = "NEEDS_MORE_TIME"
    REQUESTED_CALLBACK = "REQUESTED_CALLBACK"
    BUSY = "BUSY"
    NO_RESPONSE = "NO_RESPONSE"
    WRONG_NUMBER = "WRONG_NUMBER"
    TREATMENT_COMPLETED = "TREATMENT_COMPLETED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    DONE = "DONE"


class FollowUpType(str, enum.Enum):
    OPD_FOLLOW_UP = "OPD_FOLLOW_UP"
    TREATMENT_FOLLOW_UP = "TREATMENT_FOLLOW_UP"
    RECALL = "RECALL"
    POST_SURGERY = "POST_SURGERY"
    CUSTOM_FOLLOW_UP = "CUSTOM_FOLLOW_UP"
    LEAD_FOLLOW_UP = "LEAD_FOLLOW_UP"
    ENQUIRY_FOLLOW_UP = "ENQUIRY_FOLLOW_UP"
    PATIENT_SATISFACTION = "PATIENT_SATISFACTION"


class CommunicationChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    PHONE = "PHONE"
    IN_PERSON = "IN_PERSON"
    TASK = "TASK"
    NOTIFICATION = "NOTIFICATION"


class CommunicationStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    READ = "READ"
    FAILED = "FAILED"
    BOUNCED = "BOUNCED"


class MessageType(str, enum.Enum):
    GENERAL = "GENERAL"
    APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER"
    FOLLOW_UP = "FOLLOW_UP"
    CAMPAIGN = "CAMPAIGN"
    TRANSACTIONAL = "TRANSACTIONAL"


class EventType(str, enum.Enum):
    PATIENT_REGISTERED = "PATIENT_REGISTERED"
    PATIENT_UPDATED = "PATIENT_UPDATED"
    PATIENT_DEACTIVATED = "PATIENT_DEACTIVATED"
    LEAD_CREATED = "LEAD_CREATED"
    LEAD_CONVERTED = "LEAD_CONVERTED"
    LEAD_LOST = "LEAD_LOST"
    ENQUIRY_CREATED = "ENQUIRY_CREATED"
    ENQUIRY_CONVERTED = "ENQUIRY_CONVERTED"
    CASE_CREATED = "CASE_CREATED"
    CASE_UPDATED = "CASE_UPDATED"
    CASE_APPROVED = "CASE_APPROVED"
    CASE_COMPLETED = "CASE_COMPLETED"
    CASE_CANCELLED = "CASE_CANCELLED"
    TREATMENT_CREATED = "TREATMENT_CREATED"
    TREATMENT_STARTED = "TREATMENT_STARTED"
    TREATMENT_VISIT_COMPLETED = "TREATMENT_VISIT_COMPLETED"
    TREATMENT_COMPLETED = "TREATMENT_COMPLETED"
    TREATMENT_CANCELLED = "TREATMENT_CANCELLED"
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED"
    APPOINTMENT_MISSED = "APPOINTMENT_MISSED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_RECEIVED = "PAYMENT_RECEIVED"
    PAYMENT_OVERDUE = "PAYMENT_OVERDUE"
    FOLLOWUP_COMPLETED = "FOLLOWUP_COMPLETED"
    FOLLOWUP_FAILED = "FOLLOWUP_FAILED"
    CAMPAIGN_COMPLETED = "CAMPAIGN_COMPLETED"
    COMMUNICATION_SENT = "COMMUNICATION_SENT"
    COMMUNICATION_FAILED = "COMMUNICATION_FAILED"
    OPD_CONSULTATION_COMPLETED = "OPD_CONSULTATION_COMPLETED"
    RECALL_COMPLETED = "RECALL_COMPLETED"


class EventSource(str, enum.Enum):
    PATIENT = "PATIENT"
    LEAD = "LEAD"
    ENQUIRY = "ENQUIRY"
    CASE = "CASE"
    TREATMENT = "TREATMENT"
    APPOINTMENT = "APPOINTMENT"
    BILLING = "BILLING"
    CAMPAIGN = "CAMPAIGN"
    COMMUNICATION = "COMMUNICATION"
    FOLLOW_UP = "FOLLOW_UP"
    RECALL = "RECALL"
    CRM = "CRM"
    SYSTEM = "SYSTEM"
