// Central route metadata registry — every route should be listed here
export const routeLabels: Record<string, string> = {
  "/": "Dashboard",
  "/super-admin": "Super Admin",
  "/group-admin": "Group Admin",
  "/hospital-admin": "Hospital Admin",
  "/doctor": "Doctor",
  "/patients": "Patients",
  "/appointments": "Appointments",
  "/treatments": "Treatments",
  "/treatments/workflow": "Workflow Board",
  "/treatments/queue": "My Queue",
  "/cases": "Cases",
  "/billing": "Billing",
  "/consent-forms": "Consent Forms",
  "/doctors/availability": "Availability",
  "/consultants": "Consultants",
  "/leads": "Leads",
  "/crm/dashboard": "CRM Dashboard",
  "/crm/dashboard2": "CRM Dashboard",
  "/crm/enquiry-calendar": "Enquiry Calendar",
  "/crm/settings": "CRM Settings",
  "/whatsapp": "WhatsApp",
  "/whatsapp/templates": "WhatsApp Templates",
  "/whatsapp/broadcast": "WhatsApp Broadcast",
  "/admin/groups": "Groups",
  "/admin/hospitals": "Hospitals",
  "/admin/doctors": "Doctors",
  "/admin/expenses": "Expenses",
  "/inventory": "Inventory",
  "/exports": "Export Center",
  "/settings": "Settings",
  "/settings/clinical": "Clinical Settings",
  "/settings/whatsapp": "WhatsApp Config",
}
