// Central route metadata registry — every route should be listed here
export const routeLabels: Record<string, string> = {
  "/": "Dashboard",
  "/patients": "Patients",
  "/patients/new": "New Patient",
  "/appointments": "Appointments",
  "/appointments/new": "New Appointment",
  "/treatments": "Treatments",
  "/treatments/new": "New Treatment",
  "/treatments/workflow": "Workflow Board",
  "/treatments/queue": "My Queue",
  "/cases": "Cases",
  "/cases/new": "New Case",
  "/billing": "Billing",
  "/billing/new": "New Invoice",
  "/consent-forms": "Consent Forms",
  "/doctors/availability": "Availability",
  "/leads": "Leads",
  "/crm/dashboard2": "CRM Dashboard",
  "/crm/enquiry-calendar": "Enquiry Calendar",
  "/crm/settings": "CRM Settings",
  "/whatsapp": "WhatsApp",
  "/whatsapp/templates": "WhatsApp Templates",
  "/admin/groups": "Groups",
  "/admin/hospitals": "Hospitals",
  "/admin/doctors": "Doctors",
  "/admin/expenses": "Expenses",
  "/admin/users": "Users",
  "/admin/roles": "Roles",
  "/reports": "Reports",
  "/analytics": "Analytics",
  "/exports": "Export Center",
  "/settings": "Settings",
  "/settings/clinical": "Clinical Settings",
  "/settings/whatsapp": "WhatsApp Config",
  "/settings/notifications": "Notification Settings",
  "/settings/security": "Security",
}
