"""add_appointment_id_to_cases

Revision ID: 075bb72760a7
Revises: 3bf98d0fdb19
Create Date: 2026-06-13 12:44:32.021476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '075bb72760a7'
down_revision: Union[str, None] = '3bf98d0fdb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    if conn.engine.name == "sqlite":
        op.add_column('cases', sa.Column('appointment_id', sa.String(length=36), nullable=True))
    else:
        op.alter_column('appointments', 'appointment_type',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('CONSULTATION', 'FOLLOW_UP', 'TREATMENT', 'EMERGENCY', 'CHECKUP', 'SURGERY', name='appointmenttype'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'CONSULTATION'"))
        op.create_unique_constraint(None, 'billings', ['invoice_number'])
        op.add_column('cases', sa.Column('appointment_id', sa.String(length=36), nullable=True))
        op.alter_column('cases', 'status',
                   existing_type=sa.VARCHAR(length=12),
                   type_=sa.Enum('NEW', 'DIAGNOSIS_PENDING', 'TREATMENT_PLANNED', 'IN_PROGRESS', 'FOLLOW_UP', 'COMPLETED', 'CANCELLED', name='casestatus'),
                   existing_nullable=False)
        op.create_foreign_key(None, 'cases', 'appointments', ['appointment_id'], ['id'])
        op.create_foreign_key(None, 'follow_ups', 'appointments', ['appointment_id'], ['id'])
        op.alter_column('patients', 'status',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('NEW', 'ACTIVE', 'UNDER_TREATMENT', 'FOLLOW_UP', 'COMPLETED', 'INACTIVE', name='patientstatus'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'ACTIVE'"))
        op.alter_column('treatment_plans', 'status',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Enum('PLANNED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentplanstatus'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'PLANNED'"))
        op.alter_column('treatment_sittings', 'status',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentsittingstatus'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'PLANNED'"))
        op.create_foreign_key(None, 'users', 'admin_groups', ['admin_group_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('treatment_sittings', 'status',
               existing_type=sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentsittingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNED'"))
    op.alter_column('treatment_plans', 'status',
               existing_type=sa.Enum('PLANNED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='treatmentplanstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNED'"))
    op.alter_column('patients', 'status',
               existing_type=sa.Enum('NEW', 'ACTIVE', 'UNDER_TREATMENT', 'FOLLOW_UP', 'COMPLETED', 'INACTIVE', name='patientstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.drop_constraint(None, 'follow_ups', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.alter_column('cases', 'status',
               existing_type=sa.Enum('NEW', 'DIAGNOSIS_PENDING', 'TREATMENT_PLANNED', 'IN_PROGRESS', 'FOLLOW_UP', 'COMPLETED', 'CANCELLED', name='casestatus'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('cases', 'appointment_id')
    op.drop_constraint(None, 'billings', type_='unique')
    op.alter_column('appointments', 'appointment_type',
               existing_type=sa.Enum('CONSULTATION', 'FOLLOW_UP', 'TREATMENT', 'EMERGENCY', 'CHECKUP', 'SURGERY', name='appointmenttype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CONSULTATION'"))
    # ### end Alembic commands ###
