"""add_gst_logo_to_hospitals

Revision ID: 0767fec3b6f7
Revises: e7f8a9b0c1d2
Create Date: 2026-06-14 08:59:24.629412

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0767fec3b6f7'
down_revision: Union[str, None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_ups', 'follow_up_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.add_column('hospitals', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'logo_url')
    op.drop_column('hospitals', 'gst_number')
    op.alter_column('follow_ups', 'follow_up_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    # ### end Alembic commands ###
