"""add_initial_treatment_plan_and_clinical_findings

Revision ID: 3c1e747bc363
Revises: ac6074f8bb93
Create Date: 2026-06-17 16:40:47.173215

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3c1e747bc363'
down_revision: Union[str, None] = 'ac6074f8bb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('initial_treatment_plan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'initial_treatment_plan')
    op.drop_table('clinical_findings')
    # ### end Alembic commands ###
