"""add_soft_delete_columns

Revision ID: 68ba9a673f17
Revises: 8df8bbf00a66
Create Date: 2026-06-16 16:17:41.299015

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '68ba9a673f17'
down_revision: Union[str, None] = '8df8bbf00a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tables = [
        'admin_groups', 'appointments', 'audit_logs', 'billing_histories', 'billings',
        'campaign_recipients', 'campaigns', 'cases', 'communication_logs', 'consultant_notes',
        'consultants', 'email_templates', 'follow_up_responses', 'follow_ups',
        'hospital_monthly_expenses', 'hospital_settings', 'hospitals', 'lead_calls',
        'lead_communications', 'leads', 'notifications', 'patient_feedback', 'patients',
        'payment_transactions', 'post_ops', 'pre_ops', 'refresh_tokens', 'status_audit_logs',
        'treatment_plans', 'treatment_sittings', 'users', 'whatsapp_configs', 'whatsapp_templates',
    ]
    for table in tables:
        op.add_column(table, sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        op.add_column(table, sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        op.add_column(table, sa.Column('deleted_by', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    tables = [
        'whatsapp_templates', 'whatsapp_configs', 'users', 'treatment_sittings',
        'treatment_plans', 'status_audit_logs', 'refresh_tokens', 'pre_ops', 'post_ops',
        'payment_transactions', 'patients', 'patient_feedback', 'notifications', 'leads',
        'lead_communications', 'lead_calls', 'hospitals', 'hospital_settings',
        'hospital_monthly_expenses', 'follow_ups', 'follow_up_responses', 'email_templates',
        'consultants', 'consultant_notes', 'communication_logs', 'cases', 'campaigns',
        'campaign_recipients', 'billings', 'billing_histories', 'audit_logs',
        'appointments', 'admin_groups',
    ]
    for table in tables:
        op.drop_column(table, 'deleted_by')
        op.drop_column(table, 'deleted_at')
        op.drop_column(table, 'is_deleted')
