"""add_treatment_templates_and_template_id

Revision ID: 6ff0d3b75eb8
Revises: a1a2a3a4a5b6
Create Date: 2026-06-24 16:29:36.906514

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6ff0d3b75eb8'
down_revision: Union[str, None] = 'a1a2a3a4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_templates_hospital_id'), 'treatment_templates', ['hospital_id'], unique=False)
    op.alter_column('communication_logs', 'template_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('communication_logs', 'sent_via',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('treatment_follow_up_rules', sa.Column('treatment_template_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'treatment_follow_up_rules', 'treatment_templates', ['treatment_template_id'], ['id'])
    op.add_column('treatment_plans', sa.Column('treatment_template_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'treatment_plans', 'treatment_templates', ['treatment_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_plans', type_='foreignkey')
    op.drop_column('treatment_plans', 'treatment_template_id')
    op.drop_constraint(None, 'treatment_follow_up_rules', type_='foreignkey')
    op.drop_column('treatment_follow_up_rules', 'treatment_template_id')
    op.alter_column('communication_logs', 'sent_via',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('communication_logs', 'template_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_treatment_templates_hospital_id'), table_name='treatment_templates')
    op.drop_table('treatment_templates')
    # ### end Alembic commands ###
