"""Add export_jobs table

Revision ID: 83fb9f5c1982
Revises: 6ff0d3b75eb8
Create Date: 2026-06-24 16:52:23.912035

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '83fb9f5c1982'
down_revision: Union[str, None] = '6ff0d3b75eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_jobs')
    # ### end Alembic commands ###
