"""add_enquiries_treatment_follow_up_rules

Revision ID: 9311e1eaa137
Revises: 5931daef32da
Create Date: 2026-06-24 15:21:11.981850

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9311e1eaa137'
down_revision: Union[str, None] = '5931daef32da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_follow_up_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('follow_up_1_day', sa.Boolean(), nullable=False),
    sa.Column('follow_up_7_day', sa.Boolean(), nullable=False),
    sa.Column('recall_6_month', sa.Boolean(), nullable=False),
    sa.Column('recall_12_month', sa.Boolean(), nullable=False),
    sa.Column('custom_recall_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_follow_up_rules_hospital_id'), 'treatment_follow_up_rules', ['hospital_id'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_staff_id', sa.String(length=36), nullable=True),
    sa.Column('treatment_interest', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('next_follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry_follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enquiry_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('follow_ups', sa.Column('outcome', sa.String(length=30), nullable=True))
    op.alter_column('follow_ups', 'follow_up_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_ups', 'follow_up_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.drop_column('follow_ups', 'outcome')
    op.drop_table('enquiry_follow_ups')
    op.drop_table('enquiries')
    op.drop_index(op.f('ix_treatment_follow_up_rules_hospital_id'), table_name='treatment_follow_up_rules')
    op.drop_table('treatment_follow_up_rules')
    # ### end Alembic commands ###
