"""add period/start_date/end_date to export_jobs

Revision ID: 9391bb45d44d
Revises: 83fb9f5c1982
Create Date: 2026-06-24 18:07:06.564262

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9391bb45d44d'
down_revision: Union[str, None] = '83fb9f5c1982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('period', sa.String(length=20), nullable=True))
    op.add_column('export_jobs', sa.Column('start_date', sa.String(length=20), nullable=True))
    op.add_column('export_jobs', sa.Column('end_date', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'end_date')
    op.drop_column('export_jobs', 'start_date')
    op.drop_column('export_jobs', 'period')
    # ### end Alembic commands ###
