"""add_treatment_plan_id_to_billings

Revision ID: 9cc0dd9aace5
Revises: ff8ef131e0f2
Create Date: 2026-06-15 14:30:00.442843

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9cc0dd9aace5'
down_revision: Union[str, None] = 'ff8ef131e0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('treatment_plan_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'billings', 'treatment_plans', ['treatment_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'treatment_plan_id')
    # ### end Alembic commands ###
