"""add_expense_date_and_new_fields_to_expenses

Revision ID: 9f7ebbffc4cf
Revises: a9b8c7d6e5f4
Create Date: 2026-06-25 13:43:43.782686

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f7ebbffc4cf'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table, column):
    from sqlalchemy import inspect
    bind = op.get_bind()
    return column in [c["name"] for c in inspect(bind).get_columns(table)]


def upgrade() -> None:
    new_columns = [
        ('expense_date', sa.Date()),
        ('payment_method', sa.String(length=50)),
        ('vendor', sa.String(length=255)),
        ('invoice_number', sa.String(length=100)),
        ('receipt_path', sa.String(length=500)),
        ('notes', sa.Text()),
    ]
    for name, type_ in new_columns:
        if not column_exists('hospital_monthly_expenses', name):
            op.add_column('hospital_monthly_expenses', sa.Column(name, type_, nullable=True))
    op.execute(
        "UPDATE hospital_monthly_expenses "
        "SET expense_date = MAKE_DATE(expense_year, expense_month, 1) "
        "WHERE expense_date IS NULL"
    )
    op.alter_column('hospital_monthly_expenses', 'expense_date', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for name in ('notes', 'receipt_path', 'invoice_number', 'vendor', 'payment_method', 'expense_date'):
        if column_exists('hospital_monthly_expenses', name):
            op.drop_column('hospital_monthly_expenses', name)
    # ### end Alembic commands ###
