"""add_expense_date_and_new_fields_to_expenses

Revision ID: 9f7ebbffc4cf
Revises: a9b8c7d6e5f4
Create Date: 2026-06-25 13:43:43.782686

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f7ebbffc4cf'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('hospital_monthly_expenses', sa.Column('expense_date', sa.Date(), nullable=True))
    op.add_column('hospital_monthly_expenses', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('hospital_monthly_expenses', sa.Column('vendor', sa.String(length=255), nullable=True))
    op.add_column('hospital_monthly_expenses', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('hospital_monthly_expenses', sa.Column('receipt_path', sa.String(length=500), nullable=True))
    op.add_column('hospital_monthly_expenses', sa.Column('notes', sa.Text(), nullable=True))
    op.execute(
        "UPDATE hospital_monthly_expenses "
        "SET expense_date = MAKE_DATE(expense_year, expense_month, 1) "
        "WHERE expense_date IS NULL"
    )
    op.alter_column('hospital_monthly_expenses', 'expense_date', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_monthly_expenses', 'notes')
    op.drop_column('hospital_monthly_expenses', 'receipt_path')
    op.drop_column('hospital_monthly_expenses', 'invoice_number')
    op.drop_column('hospital_monthly_expenses', 'vendor')
    op.drop_column('hospital_monthly_expenses', 'payment_method')
    op.drop_column('hospital_monthly_expenses', 'expense_date')
    # ### end Alembic commands ###
