"""add_new_doctor_availability_system

Revision ID: ac6074f8bb93
Revises: e31ea7c50cfc
Create Date: 2026-06-17 13:45:11.470261

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ac6074f8bb93'
down_revision: Union[str, None] = 'e31ea7c50cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_working_hours',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doctor_schedules')
    # --- doctor_blocked_slots: add hospital_id as nullable first, backfill, then set NOT NULL ---
    op.add_column('doctor_blocked_slots', sa.Column('hospital_id', sa.String(length=36), nullable=True))
    op.add_column('doctor_blocked_slots', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('doctor_blocked_slots', sa.Column('updated_by', sa.String(length=36), nullable=True))
    op.execute("""
        UPDATE doctor_blocked_slots
        SET hospital_id = (SELECT hospital_id FROM users WHERE users.id = doctor_blocked_slots.doctor_id)
        WHERE hospital_id IS NULL
    """)
    op.alter_column('doctor_blocked_slots', 'hospital_id', nullable=False)
    op.create_foreign_key(None, 'doctor_blocked_slots', 'hospitals', ['hospital_id'], ['id'])

    # --- doctor_leaves: add hospital_id as nullable first, backfill, then set NOT NULL ---
    op.add_column('doctor_leaves', sa.Column('hospital_id', sa.String(length=36), nullable=True))
    op.add_column('doctor_leaves', sa.Column('created_by', sa.String(length=36), nullable=True))
    op.add_column('doctor_leaves', sa.Column('updated_by', sa.String(length=36), nullable=True))
    op.execute("""
        UPDATE doctor_leaves
        SET hospital_id = (SELECT hospital_id FROM users WHERE users.id = doctor_leaves.doctor_id)
        WHERE hospital_id IS NULL
    """)
    op.alter_column('doctor_leaves', 'hospital_id', nullable=False)
    op.create_foreign_key(None, 'doctor_leaves', 'hospitals', ['hospital_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_leaves', type_='foreignkey')
    op.drop_column('doctor_leaves', 'updated_by')
    op.drop_column('doctor_leaves', 'created_by')
    op.drop_column('doctor_leaves', 'hospital_id')
    op.drop_constraint(None, 'doctor_blocked_slots', type_='foreignkey')
    op.drop_column('doctor_blocked_slots', 'updated_by')
    op.drop_column('doctor_blocked_slots', 'created_by')
    op.drop_column('doctor_blocked_slots', 'hospital_id')
    op.create_table('doctor_schedules',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('doctor_schedules_doctor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doctor_schedules_pkey'))
    )
    op.drop_table('doctor_working_hours')
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
