"""add_follow_up_contact_tracking

Revision ID: b41d803b8558
Revises: fc884b151f2b
Create Date: 2026-06-25 11:02:03.847546

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b41d803b8558'
down_revision: Union[str, None] = 'fc884b151f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('response_status', sa.String(length=30), nullable=True))
    op.add_column('follow_ups', sa.Column('next_action', sa.String(length=30), nullable=True))
    op.add_column('follow_ups', sa.Column('contact_channel', sa.String(length=20), nullable=True))
    op.add_column('follow_ups', sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('treatment_types_name_key'), 'treatment_types', type_='unique')
    op.create_unique_constraint('uq_treatment_type_hospital_name', 'treatment_types', ['hospital_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_treatment_type_hospital_name', 'treatment_types', type_='unique')
    op.create_unique_constraint(op.f('treatment_types_name_key'), 'treatment_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('follow_ups', 'last_contact_date')
    op.drop_column('follow_ups', 'contact_channel')
    op.drop_column('follow_ups', 'next_action')
    op.drop_column('follow_ups', 'response_status')
    # ### end Alembic commands ###
