"""add_follow_up_contact_tracking

Revision ID: b41d803b8558
Revises: fc884b151f2b
Create Date: 2026-06-25 11:02:03.847546

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b41d803b8558'
down_revision: Union[str, None] = 'fc884b151f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table, column):
    from sqlalchemy import inspect
    bind = op.get_bind()
    return column in [c["name"] for c in inspect(bind).get_columns(table)]


def unique_exists(table, name):
    from sqlalchemy import inspect
    bind = op.get_bind()
    return name in [u["name"] for u in inspect(bind).get_unique_constraints(table)]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('follow_ups', 'response_status'):
        op.add_column('follow_ups', sa.Column('response_status', sa.String(length=30), nullable=True))
    if not column_exists('follow_ups', 'next_action'):
        op.add_column('follow_ups', sa.Column('next_action', sa.String(length=30), nullable=True))
    if not column_exists('follow_ups', 'contact_channel'):
        op.add_column('follow_ups', sa.Column('contact_channel', sa.String(length=20), nullable=True))
    if not column_exists('follow_ups', 'last_contact_date'):
        op.add_column('follow_ups', sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True))
    if unique_exists('treatment_types', 'treatment_types_name_key'):
        op.drop_constraint(op.f('treatment_types_name_key'), 'treatment_types', type_='unique')
    if not unique_exists('treatment_types', 'uq_treatment_type_hospital_name'):
        op.create_unique_constraint('uq_treatment_type_hospital_name', 'treatment_types', ['hospital_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if unique_exists('treatment_types', 'uq_treatment_type_hospital_name'):
        op.drop_constraint('uq_treatment_type_hospital_name', 'treatment_types', type_='unique')
    if not unique_exists('treatment_types', 'treatment_types_name_key'):
        op.create_unique_constraint(op.f('treatment_types_name_key'), 'treatment_types', ['name'], postgresql_nulls_not_distinct=False)
    for column in ('last_contact_date', 'contact_channel', 'next_action', 'response_status'):
        if column_exists('follow_ups', column):
            op.drop_column('follow_ups', column)
    # ### end Alembic commands ###
