"""add_op_no_to_patients

Revision ID: d63898a8dda3
Revises: 4b5ae6a3b003
Create Date: 2026-06-17 11:36:23.439767

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd63898a8dda3'
down_revision: Union[str, None] = '4b5ae6a3b003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('op_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'op_no')
    # ### end Alembic commands ###
