"""add_doctor_schedule_leave_blocked_slot_and_appointment_duration

Revision ID: e31ea7c50cfc
Revises: d63898a8dda3
Create Date: 2026-06-17 11:49:02.535476

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e31ea7c50cfc'
down_revision: Union[str, None] = 'd63898a8dda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_blocked_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_leaves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add columns as nullable first, backfill, then set NOT NULL
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('end_time', sa.Time(), nullable=True))
    op.execute("UPDATE appointments SET duration_minutes = 30 WHERE duration_minutes IS NULL")
    op.execute("UPDATE appointments SET end_time = appointment_time + interval '30 minutes' WHERE end_time IS NULL")
    op.alter_column('appointments', 'duration_minutes', nullable=False)
    op.alter_column('appointments', 'end_time', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'duration_minutes')
    op.drop_table('doctor_schedules')
    op.drop_table('doctor_leaves')
    op.drop_table('doctor_blocked_slots')
    # ### end Alembic commands ###
