"""add_next_appointment_date_to_treatment_plans

Revision ID: f1f7e0578091
Revises: add_patient_source_tracking
Create Date: 2026-06-14 10:41:27.239292

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f1f7e0578091'
down_revision: Union[str, None] = 'add_patient_source_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_plans', sa.Column('next_appointment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_plans', 'next_appointment_date')
    # ### end Alembic commands ###
