"""Add treatment types and update CRM workflow

Revision ID: fc884b151f2b
Revises: b8c9d0e1f2a3
Create Date: 2026-06-25 10:04:09.598634

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc884b151f2b'
down_revision: Union[str, None] = 'b8c9d0e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_treatment_types_hospital_id'), 'treatment_types', ['hospital_id'], unique=False)
    op.add_column('follow_ups', sa.Column('treatment_type_id', sa.String(length=36), nullable=True))
    op.add_column('follow_ups', sa.Column('patient_feedback', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('staff_notes', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('response_summary', sa.String(length=100), nullable=True))
    op.add_column('treatment_follow_up_rules', sa.Column('treatment_type_id', sa.String(length=36), nullable=True))
    op.alter_column('treatment_follow_up_rules', 'treatment_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'treatment_follow_up_rules', 'treatment_types', ['treatment_type_id'], ['id'])
    op.add_column('treatment_plans', sa.Column('treatment_type_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'treatment_plans', 'treatment_types', ['treatment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatment_plans', type_='foreignkey')
    op.drop_column('treatment_plans', 'treatment_type_id')
    op.drop_constraint(None, 'treatment_follow_up_rules', type_='foreignkey')
    op.alter_column('treatment_follow_up_rules', 'treatment_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('treatment_follow_up_rules', 'treatment_type_id')
    op.drop_column('follow_ups', 'response_summary')
    op.drop_column('follow_ups', 'staff_notes')
    op.drop_column('follow_ups', 'patient_feedback')
    op.drop_column('follow_ups', 'treatment_type_id')
    op.drop_index(op.f('ix_treatment_types_hospital_id'), table_name='treatment_types')
    op.drop_table('treatment_types')
    # ### end Alembic commands ###
