"""add_next_appointment_time_to_treatment_sittings

Revision ID: ff8ef131e0f2
Revises: a1b2c3d4e5f7
Create Date: 2026-06-15 13:58:19.416634

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ff8ef131e0f2'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_sittings', sa.Column('next_appointment_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_sittings', 'next_appointment_time')
    # ### end Alembic commands ###
